// Data Dummy

// Karyawan
export const tableKaryawanData = [
  {
    id: "232372",
    date: "20 Juli 2026",
    document: "Dokumen-A",
    type: "Keperluan-1",
    recipient: "Eko",
    status: "Diproses",
  },
  {
    id: "945847",
    date: "17 Juli 2024",
    document: "Dokumen-B",
    type: "Keperluan-2",
    recipient: "Erwin",
    status: "Diproses",
  },
  {
    id: "027374",
    date: "16 Juli 2024",
    document: "Dokumen-C",
    type: "Keperluan-3",
    recipient: "Deddy",
    status: "Diproses",
  },
  {
    id: "974543",
    date: "15 Juli 2024",
    document: "Dokumen-D",
    type: "Keperluan-4",
    recipient: "Budi",
    status: "Diproses",
  },
  {
    id: "023824",
    date: "10 Juli 2024",
    document: "Dokumen-E",
    type: "Keperluan-5",
    recipient: "Bachtiar",
    status: "Diajukan",
  },
  {
    id: "023824",
    date: "10 Juli 2024",
    document: "Dokumen-E",
    type: "Keperluan-5",
    recipient: "Bachtiar",
    status: "Diajukan",
  },
  {
    id: "023824",
    date: "10 Juli 2024",
    document: "Dokumen-E",
    type: "Keperluan-5",
    recipient: "Bachtiar",
    status: "Diajukan",
  },
  {
    id: "023824",
    date: "10 Juli 2024",
    document: "Dokumen-E",
    type: "Keperluan-5",
    recipient: "Bachtiar",
    status: "Diajukan",
  },
  {
    id: "023824",
    date: "10 Juli 2024",
    document: "Dokumen-E",
    type: "Keperluan-5",
    recipient: "Bachtiar",
    status: "Diajukan",
  },
  {
    id: "232372",
    date: "20 Juli 2024",
    document: "Dokumen-A",
    type: "Keperluan-1",
    recipient: "Eko",
    status: "Diajukan",
  },
  {
    id: "945847",
    date: "17 Juli 2024",
    document: "Dokumen-B",
    type: "Keperluan-2",
    recipient: "Erwin",
    status: "Diajukan",
  },
  {
    id: "027374",
    date: "16 Juli 2024",
    document: "Dokumen-C",
    type: "Keperluan-3",
    recipient: "Deddy",
    status: "Diajukan",
  },
  {
    id: "974543",
    date: "15 Juli 2024",
    document: "Dokumen-D",
    type: "Keperluan-4",
    recipient: "Budi",
    status: "Diajukan",
  },
  {
    id: "023824",
    date: "10 Juli 2024",
    document: "Dokumen-E",
    type: "Keperluan-5",
    recipient: "Bachtiar",
    status: "Diajukan",
  },
  {
    id: "023824",
    date: "10 Juli 2024",
    document: "Dokumen-E",
    type: "Keperluan-5",
    recipient: "Bachtiar",
    status: "Diajukan",
  },
  {
    id: "232372",
    date: "20 Juli 2024",
    done: "20 Juli 2024",
    document: "Dokumen-A",
    type: "Keperluan-1",
    recipient: "Eko",
    status: "Selesai",
    check: "Dokumen-A",
  },
  {
    id: "945847",
    date: "17 Juli 2024",
    done: "17 Juli 2024",
    document: "Dokumen-B",
    type: "Keperluan-2",
    recipient: "Erwin",
    status: "Ditolak",
    check: "Dokumen-B",
  },
  {
    id: "027374",
    date: "16 Juli 2024",
    done: "16 Juli 2024",
    document: "Dokumen-C",
    type: "Keperluan-3",
    recipient: "Deddy",
    status: "Selesai",
    check: "Dokumen-C",
  },
  {
    id: "974543",
    date: "15 Juli 2024",
    done: "15 Juli 2024",
    document: "Dokumen-D",
    type: "Keperluan-4",
    recipient: "Budi",
    status: "Selesai",
    check: "Dokumen-D",
  },
  {
    id: "023824",
    date: "10 Juli 2024",
    done: "10 Juli 2024",
    document: "Dokumen-E",
    type: "Keperluan-5",
    recipient: "Bachtiar",
    status: "Ditolak",
    check: "Dokumen-E",
  },
];

// Manajer
export const tableData = [
  {
    id: "763421",
    date: "10 Juli 2024",
    sender: "Siti Fadilah",
    name: "Kontrak Kerjasama Vendor.pdf",
    title: "Kontrak Kerjasama Vendor",
    type: "Procurement",
    status: "Menunggu",
    check: "Verifikasi Legal",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "845912",
    date: "12 Juli 2024",
    sender: "Ahmad Fauzi",
    name: "Rencana Anggaran Tahunan.pdf",
    title: "Rencana Anggaran 2024",
    type: "Finance",
    status: "Menunggu",
    check: "Persetujuan CFO",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "982374",
    date: "14 Juli 2024",
    sender: "Maya Putri",
    name: "Dokumen Implementasi Sistem.pdf",
    title: "Implementasi Sistem Baru",
    type: "IT",
    status: "Menunggu",
    check: "Tinjauan IT",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "126483",
    date: "18 Juli 2024",
    sender: "Ridwan Kamil",
    name: "Notulen Rapat Direksi.pdf",
    title: "Notulen Rapat Direksi",
    type: "Internal",
    status: "Menunggu",
    check: "Tinjauan Manajemen",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "453821",
    date: "20 Juli 2024",
    sender: "Nina Agustina",
    name: "Laporan Bulanan Proyek.pdf",
    title: "Laporan Proyek Bulanan",
    type: "Proyek",
    status: "Menunggu",
    check: "Persetujuan Manajer Proyek",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "647291",
    date: "22 Juli 2024",
    sender: "Dewi Sartika",
    name: "Analisis Pasar 2024.pdf",
    title: "Analisis Pasar Tahunan",
    type: "Research",
    status: "Menunggu",
    check: "Verifikasi Marketing",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "392817",
    date: "24 Juli 2024",
    sender: "Indra Wijaya",
    name: "Proposal Pengembangan Aplikasi.pdf",
    title: "Pengembangan Aplikasi Mobile",
    type: "IT",
    status: "Menunggu",
    check: "Tinjauan CTO",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "561829",
    date: "26 Juli 2024",
    sender: "Sri Hartati",
    name: "Laporan Audit Internal.pdf",
    title: "Audit Internal 2024",
    type: "Audit",
    status: "Menunggu",
    check: "Persetujuan Kepala Audit",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "728395",
    date: "28 Juli 2024",
    sender: "Rudi Santoso",
    name: "Rencana Pengembangan SDM.pdf",
    title: "Pengembangan SDM 2024",
    type: "HRD",
    status: "Menunggu",
    check: "Verifikasi HRD",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "849573",
    date: "30 Juli 2024",
    sender: "Taufik Hidayat",
    name: "Strategi Pemasaran Q3.pdf",
    title: "Strategi Pemasaran",
    type: "Marketing",
    status: "Menunggu",
    check: "Tinjauan Direktur Marketing",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "232372",
    date: "10 Juli 2024",
    sender: "Rina",
    document: "Dokumen-A",
    type: "Keperluan-1",
    status: "Selesai",
    check: "Dokumen-A",
  },
  {
    id: "945847",
    date: "15 Juli 2024",
    sender: "Beni",
    document: "Dokumen-B",
    type: "Keperluan-2",
    status: "Ditolak",
    check: "Dokumen-B",
  },
  {
    id: "027374",
    date: "16 Juli 2024",
    sender: "Lina",
    document: "Dokumen-C",
    type: "Keperluan-3",
    status: "Selesai",
    check: "Dokumen-C",
  },
  {
    id: "974543",
    date: "17 Juli 2024",
    sender: "Azhar",
    document: "Dokumen-D",
    type: "Keperluan-4",
    status: "Selesai",
    check: "Dokumen-D",
  },
  {
    id: "023824",
    date: "20 Juli 2024",
    sender: "Beddy",
    document: "Dokumen-E",
    type: "Keperluan-5",
    status: "Selesai",
    check: "Dokumen-E",
  },
  {
    id: "232372",
    date: "10 Juli 2024",
    sender: "Rina",
    document: "Dokumen-A",
    type: "Keperluan-1",
    status: "Ditolak",
    check: "Dokumen-F",
  },
  {
    id: "945847",
    date: "15 Juli 2024",
    sender: "Beni",
    document: "Dokumen-B",
    type: "Keperluan-2",
    status: "Selesai",
    check: "Dokumen-G",
  },
  {
    id: "027374",
    date: "16 Juli 2024",
    sender: "Lina",
    document: "Dokumen-C",
    type: "Keperluan-3",
    status: "Selesai",
    check: "Dokumen-H",
  },
  {
    id: "974543",
    date: "17 Juli 2024",
    sender: "Azhar",
    document: "Dokumen-D",
    type: "Keperluan-4",
    status: "Selesai",
    check: "Dokumen-I",
  },
  {
    id: "023824",
    date: "20 Juli 2024",
    sender: "Beddy",
    document: "Dokumen-E",
    type: "Keperluan-5",
    status: "Selesai",
    check: "Dokumen-J",
  },
  {
    id: "023824",
    date: "20 Juli 2024",
    sender: "Beddy",
    document: "Dokumen-E",
    type: "Keperluan-5",
    status: "Selesai",
    check: "Dokumen-J",
  },
];

// Admin
export const tableAdminDataPengguna = [
  {
    name: "Akmal Sidki razaka",
    email: "sidkirazaka@gmail.com",
    role: "Manajer bag. A",
    status: "Aktif",
  },
  {
    name: "M. Dzakiyuddin Haidar",
    email: "haidar@gmail.com",
    role: "Manajer bag. B",
    status: "Aktif",
  },
  {
    name: "Brilliant Jordan",
    email: "jordan@gmail.com",
    role: "Manajer bag. D",
    status: "Aktif",
  },
  {
    name: "Tio Adji Hidayat",
    email: "tioadji@gmail.com",
    role: "Manajer bag. C",
    status: "Nonaktif",
  },
  {
    name: "Wahyu Nata Mahendra",
    email: "wahyunatamahendra@gmail.com",
    role: "Manajer bag. E",
    status: "Aktif",
  },
  {
    name: "M. Dzakiyuddin Haidar",
    email: "haidar@gmail.com",
    role: "Manajer bag. B",
    status: "Aktif",
  },
  {
    name: "Brilliant Jordan",
    email: "jordan@gmail.com",
    role: "Manajer bag. D",
    status: "Aktif",
  },
  {
    name: "Tio Adji Hidayat",
    email: "tioadji@gmail.com",
    role: "Manajer bag. C",
    status: "Nonaktif",
  },
  {
    name: "Wahyu Nata Mahendra",
    email: "wahyunatamahendra@gmail.com",
    role: "Manajer bag. E",
    status: "Aktif",
  },
];

export const tableAdminKeperluanDokumen = [
  {
    id: "173827",
    title: "Laporan Pengajuan Cuti",
    date: "1 Agustus 2024",
  },
  {
    id: "498656",
    title: "Laporan Keuangan Perusahaan",
    date: "3 Agustus 2024",
  },
  {
    id: "869566",
    title: "Laporan Audit",
    date: "4 Agustus 2024",
  },
  {
    id: "217292",
    title: "Laporan Peminjaman Barang",
    date: "8 Agustus 2024",
  },
  {
    id: "237923",
    title: "Laporan Perkembangan Perusahaan",
    date: "13 Agustus 2024",
  },
  {
    id: "173827",
    title: "Laporan Pengajuan Cuti",
    date: "1 Agustus 2024",
  },
  {
    id: "498656",
    title: "Laporan Keuangan Perusahaan",
    date: "3 Agustus 2024",
  },
  {
    id: "869566",
    title: "Laporan Audit",
    date: "4 Agustus 2024",
  },
  {
    id: "217292",
    title: "Laporan Peminjaman Barang",
    date: "8 Agustus 2024",
  },
  {
    id: "237923",
    title: "Laporan Perkembangan Perusahaan",
    date: "13 Agustus 2024",
  },
];

export const tableAdminDataRiwayat = [
  {
    id: "235713",
    sender: "Wahyu Nata Mahendra",
    date: "1 Agustus 2024",
    title: "Dokumen Rencana Pengembangan Aplikasi",
    receiver: "Erwin",
    status: "Selesai",
  },
  {
    id: "236486",
    sender: "M. Dzakiyuddin Haidar",
    date: "4 Agustus 2024",
    title: "Laporan Pengajuan Cuti",
    receiver: "Eko",
    status: "Diproses",
  },
  {
    id: "368432",
    sender: "Wahyu Nata Mahendra",
    date: "8 Agustus 2024",
    title: "Dokumen Anggaran Pengembangan Aplikasi",
    receiver: "Eddy",
    status: "Diproses",
  },
  {
    id: "234323",
    sender: "Brilliant Jordan",
    date: "9 Agustus 2024",
    title: "Dokumen Peminjaman Kendaraan Perusahaan",
    receiver: "Erwin",
    status: "Diproses",
  },
  {
    id: "235713",
    sender: "Wahyu Nata Mahendra",
    date: "9 Agustus 2024",
    title: "Dokumen Rencana Pengembangan Aplikasi",
    receiver: "Erwin",
    status: "Selesai",
  },
  {
    id: "236486",
    sender: "M. Dzakiyuddin Haidar",
    date: "10 Agustus 2024",
    title: "Laporan Pengajuan Cuti",
    receiver: "Eko",
    status: "Diproses",
  },
  {
    id: "368432",
    sender: "Wahyu Nata Mahendra",
    date: "12 Agustus 2024",
    title: "Dokumen Anggaran Pengembangan Aplikasi",
    receiver: "Eddy",
    status: "Diproses",
  },
  {
    id: "234323",
    sender: "Brilliant Jordan",
    date: "13 Agustus 2024",
    title: "Dokumen Peminjaman Kendaraan Perusahaan",
    receiver: "Erwin",
    status: "Ditolak",
  },
];