// Data Dummy

// User Data
export const tableData = [
  {
    id: "763421",
    date: "10 Juli 2024",
    sender: "Siti Fadilah",
    name: "Kontrak Kerjasama Vendor.pdf",
    title: "Kontrak Kerjasama Vendor",
    type: "Procurement",
    status: "Menunggu",
    check: "Verifikasi Legal",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "845912",
    date: "12 Juli 2024",
    sender: "Ahmad Fauzi",
    name: "Rencana Anggaran Tahunan.pdf",
    title: "Rencana Anggaran 2024",
    type: "Finance",
    status: "Menunggu",
    check: "Persetujuan CFO",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "982374",
    date: "14 Juli 2024",
    sender: "Maya Putri",
    name: "Dokumen Implementasi Sistem.pdf",
    title: "Implementasi Sistem Baru",
    type: "IT",
    status: "Menunggu",
    check: "Tinjauan IT",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "126483",
    date: "18 Juli 2024",
    sender: "Ridwan Kamil",
    name: "Notulen Rapat Direksi.pdf",
    title: "Notulen Rapat Direksi",
    type: "Internal",
    status: "Menunggu",
    check: "Tinjauan Manajemen",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "453821",
    date: "20 Juli 2024",
    sender: "Nina Agustina",
    name: "Laporan Bulanan Proyek.pdf",
    title: "Laporan Proyek Bulanan",
    type: "Proyek",
    status: "Menunggu",
    check: "Persetujuan Manajer Proyek",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "647291",
    date: "22 Juli 2024",
    sender: "Dewi Sartika",
    name: "Analisis Pasar 2024.pdf",
    title: "Analisis Pasar Tahunan",
    type: "Research",
    status: "Menunggu",
    check: "Verifikasi Marketing",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "392817",
    date: "24 Juli 2024",
    sender: "Indra Wijaya",
    name: "Proposal Pengembangan Aplikasi.pdf",
    title: "Pengembangan Aplikasi Mobile",
    type: "IT",
    status: "Menunggu",
    check: "Tinjauan CTO",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "561829",
    date: "26 Juli 2024",
    sender: "Sri Hartati",
    name: "Laporan Audit Internal.pdf",
    title: "Audit Internal 2024",
    type: "Audit",
    status: "Menunggu",
    check: "Persetujuan Kepala Audit",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "728395",
    date: "28 Juli 2024",
    sender: "Rudi Santoso",
    name: "Rencana Pengembangan SDM.pdf",
    title: "Pengembangan SDM 2024",
    type: "HRD",
    status: "Menunggu",
    check: "Verifikasi HRD",
    fileUrl: "../Assets/exampleDoc.png",
  },
  {
    id: "849573",
    date: "30 Juli 2024",
    sender: "Taufik Hidayat",
    name: "Strategi Pemasaran Q3.pdf",
    title: "Strategi Pemasaran",
    type: "Marketing",
    status: "Menunggu",
    check: "Tinjauan Direktur Marketing",
    fileUrl: "../Assets/exampleDoc.png",
  },
];
